Creating a form with Rails
janis-jenny/Rails_Forms pull request #1
Opened 2020-11-27 21:09 UTC by thneves

- This an example of how to use forms in Rails, using the Form Helpers.
- The Form is to create a new user and edit a user.
- The form has validations attributes, error messages.

2020-11-27 23:21 UTC, bertil291utn commented
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitFlow flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
### General requirements 
- Remove all inline comments line number 7 on app/controllers/user_controllers.rb
### SECTION: edit form
- It should have comment out fom_for 
![image](https://user-images.githubusercontent.com/24902525/100487719-1e0a6900-30d8-11eb-9abe-aa656bc11e74.png)
### SECTION: new user
  `form_for`
  - Replace  text input field type input with password input

  `form_tag`
-  Use `label_tag`, `text_field_tag`, `email_field_tag`, `password_field_tag`
### SECTION: edit user
- Replace  text input field type input with password input

### Summary

-  Use right labels on `form _tag` form 
- Replace  text input field type input with password input

***

Guys work on the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-11-27 23:24 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitFlow flow you have a professional README file. 

However, in order to accomplish as the actual page, you required to do these changes, listed below:
### SECTION: edit form
- It should have comment out fom_for 
![image](https://user-images.githubusercontent.com/24902525/100487719-1e0a6900-30d8-11eb-9abe-aa656bc11e74.png)
### SECTION: new user
  `form_for`
  - Replace  text input field type input with password input

  `form_tag`
-  Use `label_tag`, `text_field_tag`, `email_field_tag`, `password_field_tag`
### SECTION: edit user
- Replace  text input field type input with password input

### Summary

-  Use right labels on `form _tag` form 
- Replace  text input field type input with password input

***

Guys work on the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-11-27 23:24 UTC, bertil291utn commented on app/controllers/users_controller.rb
> +    @user = User.new(user_params)
### Inline comment
- Please remove the inline comment

2020-11-28 18:50 UTC, blackpintz approved these changes
# Status: Approved 🎉 

**Team, before you merge, please check out the comment below. Otherwise congratulations  and good luck in your next project 😄.**

2020-11-28 18:50 UTC, blackpintz commented on app/views/users/new.html.erb
> +  <%# <%= text_field_tag(:email) %>
change line 23 to `email_field_tag`

2020-11-28 18:57 UTC, janis-jenny commented on app/views/users/new.html.erb
> +  <%# <%= text_field_tag(:email) %>
Thanks Rose 🙂

2020-11-28 18:59 UTC, merged